app:
  name: My config application
  description: Welcome to ${app.name}

my:
  values: one,two,three,TEST
  greeting: hello world TEST!!

db:
  connection: "{connectionString:  'http: //localhost: /oracle: LB: 2342', userName:  'awm-neptune', password :  'baar' }"
  host: 127.0.0.1.00
  port: 8082

management.endpoints.web.exposure.include: "*"
