app:
  name: My config application
  description: Welcome to ${app.name}

my:
  values: one,two,three
  greeting: hello world !!

db:
  connection: "{connectionString:  'http: //localhost: /oracle: LB: 2342', userName:  'awm-neptune', password :  'baar' }"
  host: 127.0.0.1
  port: 8080

management.endpoints.web.exposure.include: "*"
spring:
  profiles:
    active: test
  jpa:
    hibernate:
      ddl-auto: update